<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario INICIO',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'sfernandez@alianzafamiliar.mx',
		'to' => 'sfernandez@alianzafamiliar.mx'
	),
	'fields' => array(
		'custom_U47252' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre Completo',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre Completo\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Correo electrónico\' es obligatorio.',
				'format' => 'El campo \'Correo electrónico\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U47257' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'CURP (opcional)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U47282' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Estado',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Estado\' es obligatorio.'
			)
		),
		'custom_U47247' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Teléfono móvil',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Teléfono móvil\' es obligatorio.'
			)
		),
		'custom_U47274' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Acepto los términos y condiciones de la política de protección de datos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Acepto los términos y condiciones de la política de protección de datos\' es obligatorio.'
			)
		),
		'custom_U47261' => array(
			'order' => 6,
			'type' => 'radiogroup',
			'label' => 'Selecciona el tipo de crédito a tramitar',
			'required' => true,
			'optionItems' => array(
				'Crédito FOVISSSTE',
				'Crédito INFONAVIT',
				'Crédito Bancario'
			),
			'errors' => array(
				'required' => 'El campo \'Selecciona el tipo de crédito a tramitar\' es obligatorio.',
				'format' => 'El campo \'Selecciona el tipo de crédito a tramitar\' contiene un valor no válido.'
			)
		)
	)
);

process_form($form);
?>
